using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseApi.Models
{
    public partial class InvoiceProductItem
    {
        public int ProductID { get; set; }                      
        public Nullable<float> Quantity { get; set; }           
        public Nullable<decimal> UnitPrice { get; set; }        
        public Nullable<decimal> TotalPrice { get; set; }       
        public string AdditionalInfo { get; set; }             
        public int WarehouseID { get; set; }                    
        public Nullable<float> DiscountPercentage { get; set; }
        public Nullable<float> Quantity1 { get; set; }          
        public Nullable<float> Quantity2 { get; set; }        
        public string QuantityString { get; set; }              
        public int ID { get; set; }                             
        public Nullable<bool> AutoGenerate { get; set; }       
        public decimal VisitorPrice { get; set; }              
        public float VisitorPercentage { get; set; }           
        public Nullable<int> InvoiceID { get; set; }           
        public Nullable<decimal> Discount { get; set; }      
        public int PaymentAmount { get; set; }                  
        public short PaymentMethod { get; set; }              
        public string PaymentDate { get; set; }                 
        public Nullable<float> FractionInWhole { get; set; } 
        public Nullable<decimal> Tax { get; set; }              
        public Nullable<float> Height { get; set; }             
        public Nullable<float> Width { get; set; }              
        public Nullable<float> Thickness { get; set; }         
        public Nullable<float> Density { get; set; }            
        public Nullable<byte> UnitType { get; set; }           
        public Nullable<bool> IsAutoGenerated { get; set; }     
        public Nullable<float> Amount { get; set; }            
        public Nullable<decimal> OverheadCosts { get; set; }    
        public Nullable<bool> IsGift { get; set; }              
        public Nullable<decimal> DiscountPerItem { get; set; }  
        public Nullable<int> RowNumber { get; set; }           
        public Nullable<bool> DiscountIsGift { get; set; }      
        public Nullable<decimal> Value { get; set; }            
        public Nullable<int> PriceLevelID { get; set; }         
        public Nullable<bool> IsValueEdited { get; set; }   
    }
}
